;--------------------------------------------------
; _SCREEN.oRibon PROPERTIES 
;--------------------------------------------------
; Class name : FoxRibbon
; Version    : v 0.15
; Date       : 2017.05.25
; Author     : Guillermo Carrero (Q.E.P.D.) - Barcelona (Spain)
; Email      : foxribbonclass@gmail.com, info@rinconfox.com
;--------------------------------------------------

[RIBBON]
.nTheme=5
.nFactorBackColor=1
.BackGround=RGB(128,64,0)
.Backcolor1=RGB(128,64,0)
.Backcolor2=RGB(255,128,0)
.FormBackColor=RGB(255,128,0)
.ShadowColor=RGB(180,180,180)
.FontColor=RGB(21,66,139)
.FontColorAlternate=RGB(0,0,0)
.TabFontColor=RGB(21,66,139)
.SelectedTabFontColor=RGB(21,66,139)
.LinesColor=RGB(192,192,192)
.cFontName='Arial'
.SeeOutlineGroup=.T.
.ButtonFontColor=RGB(21,66,139)
.SelectedColor1=RGB(128,128,192)
.SelectedColor2=RGB(192,192,192)
.SelectedButtonFontColor=RGB(0,0,0)
.AutoTabClick=.F.
.ShowAnimationPage=.F.
.AnimationFaster=5
.InEditBackColor=RGB(255,238,194)
.InEditBackDisable=RGB(240,240,240)
.InEditForeColor=RGB(0,0,0)
.InEditForeDisable=RGB(128,128,128)
.InEditFrameColor=RGB(255,0,0)
.RowBackColor=RGB(0,64,128)
.RowFontColor=RGB(255,255,255)
